pipeline {
    agent any

    stages {
        stage('Use Credentials') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'hello-world', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    echo "Username: ${USERNAME}"
                    echo "Password: ${PASSWORD}" // ⚠️ For learning ONLY
                }
            }
        }
    }
}
