pipeline {
    agent any

    stages {
        stage('Use Credentials') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'hello-world', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    echo "Username: ${USERNAME}"
                    sh 'curl -u $USERNAME:$PASSWORD https://httpbin.org/basic-auth/user/passwd'
                }
            }
        }
    }
}
